//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCdemo02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        //Its Automatically converted Coloum's into Methodes. And its called Maping. 
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string MailID { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
    }
}
